# Generated by Django 3.1.3 on 2020-11-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=80)),
                ('building_acronym', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_credits', models.PositiveSmallIntegerField()),
                ('max_credits', models.PositiveSmallIntegerField()),
                ('course_description', models.TextField()),
                ('course_title', models.CharField(max_length=100)),
                ('course_prefix', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('max_capacity', models.PositiveSmallIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.building')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_program', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Arrangment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangment', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_semester', models.CharField(max_length=10)),
                ('second_semester', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.PositiveSmallIntegerField()),
                ('max_registration', models.PositiveSmallIntegerField()),
                ('max_waitlist', models.PositiveSmallIntegerField()),
                ('waitlist', models.PositiveSmallIntegerField()),
                ('students_registered', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('year', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.faculty')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.room')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.semester')),
                ('sub_program_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='serendipity.sub_program')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='table_arrangment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.table_arrangment'),
        ),
        migrations.CreateModel(
            name='Preferred_Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.days')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.faculty')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Preferred_Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.faculty')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Preferred_Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.faculty')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.room')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Preferred_Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.days')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.faculty')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Preferred_Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('credit_amount', models.PositiveSmallIntegerField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.faculty')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Preferred_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('year', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.course')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.faculty')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.semester')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.location'),
        ),
        migrations.CreateModel(
            name='Enrollment_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_course_status', models.DecimalField(decimal_places=4, max_digits=7)),
                ('from_waitlist', models.BooleanField()),
                ('dropped', models.BooleanField()),
                ('course_section_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.section_info')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.location')),
                ('student_degree', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.degree')),
                ('student_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.student_year')),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.sub_program')),
            ],
        ),
        migrations.CreateModel(
            name='DayOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.days')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='serendipity.section_info')),
            ],
        ),
        migrations.CreateModel(
            name='Course_requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='serendipity.course')),
                ('required_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required', to='serendipity.course')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog_year_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serendipity.degree')),
            ],
        ),
    ]
