# Generated by Django 3.1.3 on 2020-11-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serendipity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='first_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_semester', to='serendipity.semester'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='second_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_semester', to='serendipity.semester'),
        ),
    ]
